# Generated by Django 4.0.1 on 2022-01-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.IntegerField(choices=[(1, 'Web Developer'), (2, 'QA'), (3, 'DevOps')]),
        ),
    ]
