# Generated by Django 4.0.1 on 2022-01-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.CharField(choices=[('Softuni', 'Softuni'), ('Google', 'Google')], default='Softuni', max_length=7),
            preserve_default=False,
        ),
    ]
