# Generated by Django 4.0.1 on 2022-02-01 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_remove_user_id_alter_user_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
