# Generated by Django 4.0.1 on 2022-02-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_remove_employee_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('first_name',)},
        ),
    ]
