# Generated by Django 4.0.1 on 2022-02-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
    ]
