# Generated by Django 4.0.1 on 2022-03-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_remove_employee_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
