# Generated by Django 4.0 on 2022-01-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed_by',
            field=models.CharField(max_length=38, null=True),
        ),
    ]
