# Generated by Django 4.0 on 2022-01-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_categories_todo_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
