# Generated by Django 4.0.1 on 2022-01-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker_app', '0002_alter_expenses_options_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='expenses',
            name='image_url',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='expenses',
            name='price',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='budget',
            field=models.IntegerField(default=None),
        ),
    ]
