# Generated by Django 4.0.1 on 2022-01-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker_app', '0004_remove_expenses_description_remove_expenses_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='expenses',
            name='price',
            field=models.FloatField(default=None),
        ),
    ]
